version: "3"
services:
  mysqldb:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    networks:
      - financer-network
    restart: always
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: financer    
networks:
  financer-network:
    driver: bridge