version: "3"
services:
  config-server:
    container_name: config-server
    build: ./config-server
    ports: 
      - "8888:8888"
    networks:
      - financer-network
    restart: always
  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports: 
      - "8761:8761"
    networks:
      - financer-network
    restart: always  
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports: 
      - "3306:3306"
    networks:
      - financer-network
    restart: always
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: financer    
networks:
  financer-network:
    driver: bridge