version: "3"
services:
  config-server:
    container_name: config-server
    build: ./config-server
    ports: 
      - "8888:8888"
    networks:
      - financer-network
    restart: always
  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports: 
      - "8761:8761"
    networks:
      - financer-network
    restart: always  
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports: 
      - "3306:3306"
    networks:
      - financer-network
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: financer
      MYSQL_ROOT_PASSWORD: s3cr3t      
  users-api_1:
    container_name: users-api_1
    build: ./users-api
    ports: 
      - "8081:8081"
    networks:
      - financer-network
    restart: always    
    links: 
      - config-server
      - eureka-server
      - mysqldb
    depends_on:
      - config-server
      - eureka-server
      - mysqldb
    entrypoint: /bin/sh
    environment: 
      MYSQL_URL: jdbc:mysql://mysqldb:3306/financer
      MYSQL_USER: root
      MYSQL_PASSWORD: s3cr3t
      EUREKA_SERVER: http://eureka-server:8761/eureka/
    command: >
      -c "
      while ! (nc -z config-server 8888 && nc -z eureka-server 8761 && nc -z mysqldb 3306); do sleep 5; echo 'Waiting for other services to start-up...'; done;
      java -Djava.security.egd=file:/dev/./urandom -jar -Dserver.port=8081 -Dspring.profiles.active=dev /users-api.jar"
  users-api_2:
    container_name: users-api_2
    build: ./users-api
    ports: 
      - "8082:8082"
    networks:
      - financer-network
    restart: always    
    links: 
      - config-server
      - eureka-server
      - mysqldb
    depends_on:
      - config-server
      - eureka-server
      - mysqldb
    entrypoint: /bin/sh
    environment: 
      MYSQL_URL: jdbc:mysql://mysqldb:3306/financer
      MYSQL_USER: root
      MYSQL_PASSWORD: s3cr3t
      EUREKA_SERVER: http://eureka-server:8761/eureka/
    command: >
      -c "
      while ! (nc -z config-server 8888 && nc -z eureka-server 8761 && nc -z mysqldb 3306); do sleep 5; echo 'Waiting for other services to start-up...'; done;
      java -Djava.security.egd=file:/dev/./urandom -jar -Dserver.port=8082 -Dspring.profiles.active=dev /users-api.jar"
  cards-api:
    container_name: cards-api
    build: ./cards-api
    ports: 
      - "8083:8083"
    networks:
      - financer-network
    restart: always    
    links: 
      - config-server
      - eureka-server
      - mysqldb
      - users-api_1
      - users-api_2
    depends_on:
      - config-server
      - eureka-server
      - mysqldb
      - users-api_1
      - users-api_2
    entrypoint: /bin/sh
    environment: 
      MYSQL_URL: jdbc:mysql://mysqldb:3306/financer
      MYSQL_USER: root
      MYSQL_PASSWORD: s3cr3t
      EUREKA_SERVER: http://eureka-server:8761/eureka/
    command: >
      -c "
      while ! (nc -z config-server 8888 && nc -z eureka-server 8761 && nc -z mysqldb 3306); do sleep 5; echo 'Waiting for other services to start-up...'; done;
      java -Djava.security.egd=file:/dev/./urandom -jar -Dspring.profiles.active=dev /cards-api.jar"
  accounts-api:
    container_name: accounts-api
    restart: always
    build: ./accounts-api
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - "mongodb"
      - users-api_1
      - users-api_2
    env_file: ./accounts-api/.env
    networks:
      - financer-network    
  mongodb:
    image: mongo
    container_name: mongodb
    ports: 
      - "27017:27017"
    networks:
      - financer-network 
networks:
  financer-network:
    driver: bridge