version: "3"
services:
  accounts-api:
    container_name: accounts-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - "mongodb"
    env_file: .env
    networks:
      - accounts-network
  mongodb:
    image: mongo
    container_name: mongodb
    ports: 
      - "27017:27017"
    networks:
      - accounts-network    
networks:
  accounts-network:
    driver: bridge